# Generated by Django 3.2.3 on 2021-05-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthCountry',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(choices=[('A', 'Actor'), ('D', 'Director')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
