# Generated by Django 3.2.3 on 2021-05-30 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20210530_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('releaseDate', models.DateField()),
                ('actors', models.ManyToManyField(related_name='films_played_in', to='rest.Person')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='films_created', to='rest.person')),
            ],
        ),
    ]
