# Generated by Django 3.2.3 on 2021-05-30 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publicationDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
